//Automatically generated by PythonVarGen.py
NAME CARTFRAMEIEC_;
{
	no_var
}
USER;
IMPLEMENT IIecMapable;

VAR USER

	x : MAPTO LREAL;
	y : MAPTO LREAL;
	z : MAPTO LREAL;
	a : MAPTO LREAL;
	b : MAPTO LREAL;
	c : MAPTO LREAL;
END_VAR
ROUTINE MapToIecTarget(CONST iecTargetName : STRING; CONST OPTIONAL arrayIdxOffset : DINT)

   // check if this cartposiec is declared within a tc interface or as global iec var
   IF IS_USED(arrayIdxOffset) THEN
      mIecData := MAPX(iecTargetName + "@" + STR(arrayIdxOffset * cIecDataSize));
   ELSE
      mIecData := MAPX(iecTargetName);
   END_IF;   
   IF IS_MAPPED(mIecData) THEN
	x := MAP(mIecData.x);
	y := MAP(mIecData.y);
	z := MAP(mIecData.z);
	a := MAP(mIecData.a);
	b := MAP(mIecData.b);
	c := MAP(mIecData.c);
END_IF;
   // finally check if mapping is ok
   mDataMapped := CheckIsMapped();
END_ROUTINE

ROUTINE CheckIsMapped(CONST OPTIONAL optional : BOOL) : BOOL

   IF IS_MAPPED(mIecData)
		AND IS_MAPPED(x) AND IS_MAPPED(y) AND IS_MAPPED(z) AND IS_MAPPED(a) AND IS_MAPPED(b) AND IS_MAPPED(c) THEN
	RETURN TRUE;
   ELSE
      // not all data mapped
      IF NOT (IS_USED(optional) AND optional) THEN
         RcSetWarning(INSTANCE_ID(), eRcErrorVarNotMapped, INSTANCE_NAME(), "CARTFRAMEIEC");
      END_IF;
      RETURN FALSE;
   END_IF;    
END_ROUTINE
(*-----------------------------------------------------------------------------
* private
*)


TYPE PRIVATE
   // representation of PLC data structure
   
   TIecData : STRUCT
		x : LREAL;
		y : LREAL;
		z : LREAL;
		a : LREAL;
		b : LREAL;
		c : LREAL;
   END_STRUCT;
END_TYPE


VAR PRIVATE
   mIecData : MAPTO TIecData;
   mDataMapped : BOOL;
END_VAR


CONSTANT PRIVATE
   cIecDataSize : DINT := 48;
END_CONSTANT
