//Automatically generated by PythonVarGen.py
//Author : Doug Smith

NAME OVLIEC_;
{
	no_var
}
USER;
IMPLEMENT IIecMapable;

VAR USER

	ovlType : MAPTO DINT;
	ovlPercent : MAPTO DINT;
	posDist : MAPTO REAL;
	oriDist : MAPTO REAL;
	linAxDist : MAPTO REAL;
	rotAxDist : MAPTO REAL;
	vConst : MAPTO BOOL;
END_VAR
ROUTINE MapToIecTarget(CONST iecTargetName : STRING; CONST OPTIONAL arrayIdxOffset : DINT)

   // check if this cartposiec is declared within a tc interface or as global iec var
   IF IS_USED(arrayIdxOffset) THEN
      mIecData := MAPX(iecTargetName + "@" + STR(arrayIdxOffset * cIecDataSize));
   ELSE
      mIecData := MAPX(iecTargetName);
   END_IF;   
   IF IS_MAPPED(mIecData) THEN
	ovlType := MAP(mIecData.ovlType);
	ovlPercent := MAP(mIecData.ovlPercent);
	posDist := MAP(mIecData.posDist);
	oriDist := MAP(mIecData.oriDist);
	linAxDist := MAP(mIecData.linAxDist);
	rotAxDist := MAP(mIecData.rotAxDist);
	vConst := MAP(mIecData.vConst);
END_IF;
   // finally check if mapping is ok
   mDataMapped := CheckIsMapped();
END_ROUTINE

ROUTINE CheckIsMapped(CONST OPTIONAL optional : BOOL) : BOOL

   IF IS_MAPPED(mIecData)
		AND IS_MAPPED(ovlType) AND IS_MAPPED(ovlPercent) AND IS_MAPPED(posDist) AND IS_MAPPED(oriDist) AND IS_MAPPED(linAxDist) AND IS_MAPPED(rotAxDist) AND IS_MAPPED(vConst) THEN
	RETURN TRUE;
   ELSE
      // not all data mapped
      IF NOT (IS_USED(optional) AND optional) THEN
         RcSetWarning(INSTANCE_ID(), eRcErrorVarNotMapped, INSTANCE_NAME(), "OVLIEC");
      END_IF;
      RETURN FALSE;
   END_IF;    
END_ROUTINE
(*-----------------------------------------------------------------------------
* private
*)


TYPE PRIVATE
   // representation of PLC data structure
   
   TIecData : STRUCT
		ovlType : DINT;
		ovlPercent : DINT;
		posDist : REAL;
		oriDist : REAL;
		linAxDist : REAL;
		rotAxDist : REAL;
		vConst : BOOL;
   END_STRUCT;
END_TYPE


VAR PRIVATE
   mIecData : MAPTO TIecData;
   mDataMapped : BOOL;
END_VAR


CONSTANT PRIVATE
   cIecDataSize : DINT := 28;
END_CONSTANT
